steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/python-executor:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/python-executor:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run with elevated privileges for nsjail
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'python-executor'
      - '--image'
      - 'gcr.io/$PROJECT_ID/python-executor:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '60'
      - '--execution-environment'
      - 'gen2'
      - '--cpu-boost'

images:
  - 'gcr.io/$PROJECT_ID/python-executor:$COMMIT_SHA'